config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :gardens do
    resources :bookings
  end
  get "dashboards", to: "dashboards#account"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :garden
  belongs_to :user

  validates :user_id, presence: true
  validates :garden_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/garden.rb
class Garden < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings
  belongs_to :user

  validates :price, presence: true, numericality: true
  validates :square_meters, presence: true, numericality: true
  validates :description, presence: true
  validates :address, presence: true
  validates :title, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_by_address_and_square_meters,
  against: [:address, :square_meters],
  using: {
  tsearch: { prefix: true }
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :gardens
  # has_many :gardens, through: :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Pundit
  # protect_from_forgery
   before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = booking.new(booking_params)
    if @booking.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @garden_id = @booking.garden_id
    @booking.destroy
    redirect_to garden_path(@garden_id)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @booking = Booking.new
    authorize @garden
    authorize @booking
  end

  def create
  @start_date = Date.civil(booking_params[:"start_date(1i)"].to_i,
                         booking_params[:"start_date(2i)"].to_i,
                         booking_params[:"start_date(3i)"].to_i)

  @end_date   = Date.civil(booking_params[:"end_date(1i)"].to_i,
                         booking_params[:"end_date(2i)"].to_i,
                         booking_params[:"end_date(3i)"].to_i)
    # start_date = "#{booking_params[start_date(li1)]}/#{booking_params[start_date(li2)]}/#{booking_params[start_date(li3)]}"
    # Date.parse start_date
    # end_date = "#{booking_params[end_date(li1)]}/#{booking_params[end_date(li2)]}/#{booking_params[end_date(li3)]}"
    # Date.parse end_date
    @garden = Garden.find(params[:garden_id])
    @booking = Booking.new(start_date: @start_date, end_date: @end_date)
    @booking.garden = @garden
    @booking.user = current_user

    authorize @booking

    if @booking.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @garden_id = @booking.garden_id
    @booking.destroy
    redirect_to garden_path(@garden_id)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_before_action :authenticate_user!, only: :account

  def account
    @gardens = Garden.where(user_id: current_user)
    if @gardens == []
      @gardens = []
      @bookings = []
      current_user.bookings.each do |booking|
        @gardens << booking.garden
        @bookings << booking
      end
      @company = true
      authorize @gardens
    else
      @company = false
      @bookings = Booking.all
      authorize @gardens
    end
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :find_garden, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    if params[:search_query].present?
      sql_query = " \
      gardens.address @@ :query \
      AND gardens.category @@ :query_bis \
      "
      @gardens = policy_scope(Garden.where(sql_query, query: "%#{params[:search_query]}%", query_bis: "%#{params[:sq_category]}%"))
      # @filtered_gardens = @gardens.select(category: params[:sq_category])
      # .where(category: params[:sq_category])

    else
      @gardens = policy_scope(Garden)
    end
  end

  def new
    @garden = Garden.new
    authorize @garden
  end

  def show
    @markers =
      {
        lat: @garden.latitude,
        lng: @garden.longitude
      }
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user
    authorize @garden
    if @garden.square_meters < 100
      @garden.category = "small"
    elsif @garden.square_meters > 100 && @garden.square_meters < 200
      @garden.category = "medium"
    elsif @garden.square_meters > 200 && @garden.square_meters < 500
      @garden.category = "large"
    elsif @garden.square_meters > 500
      @garden.category = "extra large"
    end
    if @garden.save!
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def edit; end

  def update
    @garden.update(garden_params)
    if @toy.save!
      redirect_to garden_path(@garden)
    else render :new
    end
  end

  def destroy
    @garden.destroy
    redirect_to gardens_path
  end

  private

  def garden_params
    params.require(:garden).permit(:title, :description, :address, :square_meters, :price, :photo, :category)
  end

  def find_garden
    @garden = Garden.find(params[:id])
    authorize @garden
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
	<h1>Your booking with us :</h1>
	<%= simple_form_for [@garden, @booking] do |f| %>
	<div id="dates">
		<p>The date you start renting :</p>
		<%= f.input_field :start_date, :order => [:day, :month, :year] %>
		<br>
	</div>
	<div class="dates">
		<p>The date you finish renting :</p>
		<%= f.input_field :end_date, :order => [:day, :month, :year] %>
	</div>

	<div id="price">
		<p>price per day : <%= @garden.price%>$</p>
	</div>
		<%= f.submit "Book",  class: "button"%>
		<% end %>
</div>

<!-- <form action="">
  <input type="date" name="bday">
  <input type="date" name="bday">
</form> -->

app/views/dashboards/account.html.erb
<div class=container>
  <% if @company == true %>
    <h1>Your bookings</h1>
    <div class="cards">
      <% @bookings.each do |booking| %>
        <div class="card-trip">
        <%= cl_image_tag booking.garden.photo, height: 300, width: 400, crop: :fill %>
          <div class="card-trip-infos">
            <div>
              <h2><%= booking.garden.title %></h2>
              <p><%= booking.garden.description %></p>
              <p><%= booking.garden.square_meters %> square meters</p>
              <p><b>Booked from <%= booking.start_date %> until <%= booking.end_date %> </b> </p>
            </div>
            <h2 class="card-trip-pricing"><%= booking.garden.price %>€</h2>
          </div>


              <div class="buttons-row">
                <button class ="button">
                    <%= link_to "show garden", garden_path(booking.garden)  %>
                  </button>
              </div>
        </div>
      <% end %>
  <% else %>
    <h1>Your Gardens </h1>
    <div class="cards">
      <% @gardens.each do |garden| %>
        <div class="card-trip">
        <%= cl_image_tag garden.photo, height: 300, width: 400, crop: :fill %>
          <div class="card-trip-infos">
            <div>
              <h2><%= garden.title %></h2>
              <p><%= garden.description %></p>
              <p><%= garden.square_meters %> square meters</p>
              <% if @bookings.where(garden_id: garden) == [] %>
                <p><b>Currently no bookings</b></p>
              <% else %>
                <p><b>Booked from <%= @bookings.where(garden_id: garden).last.start_date %> until <%= @bookings.where(garden_id: garden).last.end_date %> </b> </p>
              <% end %>

            </div>



            <h2 class="card-trip-pricing"><%= garden.price %>€</h2>
          </div>

              <div class="buttons-row">
                <button class ="button">
                    <%= link_to "show garden", garden_path(garden)  %>
                  </button>
                <% if policy(garden).edit? %>
                  <button class ="button">
                    <%= link_to "edit garden", edit_garden_path(garden) %>
                  </button>
                <% end %>
                <% if policy(garden).destroy? %>
                  <button class ="button">
                    <%= link_to "remove garden", garden_path(garden), method: :delete%>
                  </button>
                <% end %>

              </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/gardens/index.html.erb
<div class="container">
  <h1> Gardens </h1>
  <%= form_tag gardens_path, method: :get do %>
  <%= text_field_tag :query,
  params[:query],
  class: "form-control",
    placeholder: "Find your garden"
    %>
    <% end %>
    <div class="cards">
      <% @gardens.each do |garden| %>
      <div class="card-trip">
        <%= cl_image_tag garden.photo %>
        <div class="card-trip-infos">
          <div>
            <h2><%= garden.title %></h2>
            <p><%= garden.description %></p>
            <p><%= garden.square_meters %> square meters</p>
          </div>
          <h2 class="card-trip-pricing"><%= garden.price %>€</h2>
        </div>
        <div class="buttons-row">
          <button class ="button">
            <%= link_to "See details", garden_path(garden)  %>
          </button>
          <% if policy(garden).destroy? %>
          <button class ="button">
            <%= link_to "Remove", garden_path(garden), method: :delete%>
          </button>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/gardens/new.html.erb
<div class="container">
  <%= simple_form_for @garden do |f| %>
	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :address %>
	<%= f.input :price %>
	<%= f.input :square_meters %>
	<%= f.input :photo %>
	<%= f.input :photo_cache, as: :hidden %>

	<%= f.button :submit, "Add garden", class: "button" %>
  <% end %>
</div>

app/views/gardens/show.html.erb
<div class="container">
  <div class="garden-card">
    <div class="text">
      <div class="titles">
        <h2><%= @garden.title %></h2>
        <h5><%= @garden.description %></h5>
      </div>
      <br><br>
      <div class="details">
        <p>Address: <%= @garden.address  %></p>
        <p>Square meters: <%= @garden.square_meters %></p>
        <p>Price: <%= @garden.price %> €</p>
      </div>
      <div class="buttons">
        <button class="button">
          <%= link_to "Book now", new_garden_booking_path(@garden)  %>
        </button>
        <button class="button">
          <%= link_to "All gardens", gardens_path %>
        </button>
      </div>
    </div>
    <%= cl_image_tag @garden.photo, height: 300, width: 400, crop: :fill %>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--not the same line as in the video front-end 0:31
  -->
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Gardens</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Mukta&display=swap" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>

  <%= render "shared/navbar" %>
  <div class="flex-wrapper">
    <%= yield %>
    
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render "shared/footer" %>
  </body>
  </html>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&display=swap" rel="stylesheet">
<div class="banner">
  <div class="banner-items">
    <h1>Solar Garden</h1>
    <h2>Find a garden to install your solar panels</h2>
    <div class="searchbar">
      <%= render "shared/searchbar" %>
    </div>
  </div>
</div>

<%= render "shared/explanation" %>
<%= render "shared/partners" %>

app/views/shared/_cards.html.erb
<div class="card-trip">
    <img src="http://www.sahomeowner.co.za/wp-content/uploads/2013/07/August-Garden-22.jpg">
      <div class="card-trip-infos">
        <div>
          <h2><%= garden.title %></h2>
          <p><%= garden.description %></p>
          <p><%= garden.square_meters %> square meters</p>
        </div>
        <h2 class="card-trip-pricing"><%= garden.price %>€</h2>
      </div>
          <div class="d-flex justify-content-around align-items-end">
            <% if policy(garden).edit? %>
              <button class ="btn">
                <%= link_to "edit garden", edit_garden_path(garden) %>
              </button>
            <% end %>
              <button class ="btn">
                <%= link_to "show garden", garden_path(garden)  %>
              </button>
            <% if policy(garden).destroy? %>
              <button class ="btn">
                <%= link_to "remove garden", garden_path(garden), method: :delete%>
              </button>
            <% end %>

          </div>
    </div>

app/views/shared/_explanation.html.erb
<div class="everything">
  <h1>How it works</h1>
    <div class="explanations">

      <div class="explanation">
        <%= image_tag "explanation1.jpeg", class: "img" %>
        <h4>Find a garden</h4>
        <p>We have lots of gardens in our database, seriously you guys, have a scroll. And you kinda need a garden for your solar panels so...</p>
      </div>

      <div class="explanation">
        <%= image_tag "explanation2.jpeg", class: "img" %>
        <h4>Pay a small fee</h4>
        <p>And you'll make the gardener happy cause you pay him and he'll be able to spend it cause he's a victim of consumerism</p>
      </div>


      <div class="explanation">
        <%= image_tag "explanation3.jpeg", class: "img" %>
        <h4>Greener world</h4>
        <p>Thanks to you cause you're like contributing to renewable energy and that's like totally important right</p>
      </div>

    </div>
  </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    ©2019 Solar Garden, Inc. All rights reserved.
  </div>
  <div class="footer-urls">
    <a href="#">Contact us</a>
    <a href="#">Privacy policy</a>
    <a href="#">Conditions</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "sun.jpeg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">



      <li class="nav-item active">
        <%= link_to "Host your garden", new_garden_path, class: "nav-link" %>
      </li>
      <% if !user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", user_session_path, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Dashboard", dashboards_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path,  method: :delete, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_partners.html.erb
<div class="everything-partners">
    <h1>They already trust us</h1>
    <div class="explanations-partners">

      <div class="explanation">
        <%= image_tag "lampiris.jpeg", class: "img" %>
      </div>

      <div class="explanation">
        <%= image_tag "eneco.jpeg", class: "img" %>
      </div>


      <div class="explanation">
        <%= image_tag "engie.jpeg", class: "img" %>
      </div>

      <div class="explanation">
        <%= image_tag "mega.jpeg", class: "img" %>
      </div>

    </div>
  </div>

app/views/shared/_search.html.erb
_search.html.erb

app/views/shared/_searchbar.html.erb
<div class="searchbar">
  <%= simple_form_for :search, url: gardens_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <div class="inputs">
        <%= text_field_tag :search_query,
          params[:search_query],
          class: "form-control string required",
          placeholder: "Where?"
        %>
        <select class="form-control string required" name="sq_category" id="search_query">
          <option value="">How many m²</option>
          <option value="small">Under 100 m²</option>
          <option value="medium">Between 100 m² and 200 m²</option>
          <option value="large">Between 200 m² and 500 m²</option>
          <option value="extra large">Over 500 m²</option>
          <option value="">No preference</option>
        </select>
      </div>
      <br>
      <button class='button'>
        <%= link_to 'Search', gardens_path  %>
      </button>
    </div>


  <% end %>
</div>